### ISSUE TITLE
Missing floors and textures

### ISSUE THREAD

**Issue by CartridgeGen** [ptitSeb/glshim#1]
Hello! 
I tried using GDB with the LIBGL and the program I'm trying to run but the GDB program states nothing out of place while in-game, the floor and some textures are missing, even though the same textures elsewhere in the game would be perfectly ok. I've also tried debugging the shared library itself and again nothing is out of place. Maybe what the game is looking for is non-existant in the shim?
Here's a picture http://imgur.com/XUy8rx9
and a GDB output http://pastebin.com/XKxQ0cXi

As you can see in the picture, under the green armor, the texture is gone, right beside the armor,
the same texture is used and is visible. My guess would be brightmaps. But I can't confirm that since no GDB output from either shim or program can tell me what is wrong.

**Comment by ptitSeb** [comment]
@CartridgeGen : I guess this is either gzdoom or Zandronum running in OpenGL mode.
I had this issue too, but the problem is not is glshim.

On gzdoom, in src/nodebuild_utility.cpp, around line 70
change
```
return angle_t(ang * rad2bam) << 1;
```
to
```
return (angle_t((int)(ang * rad2bam))) << 1;
```

Do something similar for zandronum.
Problem is with the ARM handling of negative float -> unsigned int in a different way then x86 does.

**Comment by CartridgeGen** [comment]
Wow thanks! Ill try that! Merci beacoup mon ami.

Bonne journee!

**Comment by ptitSeb** [comment]
De rien (si ça fonction).

And if it works, please report so I can close the ticket :)

**Comment by CartridgeGen** [comment]
Ca fonctionner! Les murs et les planchers sont maintenant visible! Wow merci beaucoup de votre aide mon ami! Il reste juste a trouver un remplacement de FMOD.

**Comment by ptitSeb** [comment]
Remplacer par OpenAL par exemple ?

Here is a complete diff (from hg diff) from my build of zandronum for the Pandora. There is an OpenAL backend for sound (taken from an experiemental and unmaintained openal branch from zdoom). To be adapted a bit, there are still pieces from Pandora build (like keymap) : https://pyra-handheld.com/boards/threads/zdoom.73406/#post-1274881 (you will probably need an account to download the file).
