### ISSUE TITLE
NPOT causes small visual glitch in naev

### ISSUE THREAD

**Issue by petevine** [ptitSeb/glshim#11]
NPOT textures has to be ticked in the video settings and then:

```shell 
$ LIBGL_NPOT=2 naev
LIBGL: Initialising glshim
LIBGL:loaded: libGLESv1_CM.so
LIBGL:loaded: libEGL.so
 Naev v0.6.1
 Sea of Darkness
LIBGL: built on Nov  1 2016 21:30:52
LIBGL: Extension GL_OES_point_sprite detected and used
LIBGL: Extension GL_OES_point_size_array detected
LIBGL: Extension GL_OES_framebuffer_object detected and used
LIBGL: Extension GL_OES_packed_depth_stencil detected and used
LIBGL: Extension GL_OES_depth24 detected and used
LIBGL: Extension GL_OES_rgb8_rgba8 detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888 detected
LIBGL: Extension GL_OES_depth_texture detected and used
LIBGL: Max texture size: 4096
LIBGL: Texture Units: 8, Max lights: 8
LIBGL: Implementation Read is GL_RGB/GL_UNSIGNED_SHORT_5_6_5
LIBGL: Expose GL_ARB_texture_non_power_of_two extension
LIBGL: Current folder is:/home/odroid
libGL: warning, gles_glBlendFuncSeparate is NULL
````

leads to clearly visible planet tiles outlines (or whatever that is):
![naev-glitch](https://cloud.githubusercontent.com/assets/12054457/19907989/7828849e-a081-11e6-8172-894d4613b711.jpg)

**Comment by ptitSeb** [comment]
Yes, LIBGL_NPOT=2 expose a function that is not completly supported for now. LIBGL_NPOT=1 is 100% emulated, but not 2 for now. I may work on that, but real support as not been mandatory for anything yet.

**Comment by petevine** [comment]
I see, `Expose limited NPOT extension` sounded as if it might be too limited so I never tried that. My bad! :)

**Comment by ptitSeb** [comment]
Limited NPOT is : can use texture not NPOT, but cannot use Repeat or Mirror on NPOT, and no Mipmap neither.
basicaly what glshim does is can use NPOT texture (by creating a bigger NPOT texture), and so no Repeat or Mirror. Mipmap is supported but can lead to some artifact on the border (as you have already seen). That effect can probably be mitigated for textures with an alpha channel if I upload an empty texture first.

Full NPOT can do whatever they wants. Emulating that on non-NPOT hardware would mean resizing a non-NPOT texture to NPOT, meaning a lot of computational power at each upload, plus some artefact du to the resizing (espcially on SubImage manipulations).

**Comment by ptitSeb** [comment]
I'll close this ticket.

**Comment by petevine** [comment]
Talking of glitches, just remembered this unrelated mouse pointer problem in TOME:

![cursor](https://cloud.githubusercontent.com/assets/12054457/19909808/9605f570-a089-11e6-9f10-6f8d7e686890.jpg)

` LIBGL_NOLUMALPHA` makes no difference and capturing the screen normally shows just the regular X-window mouse pointer.

**Comment by ptitSeb** [comment]
did you retry with latest changes (with added Pixmap, PBuffer and multiple glX Context, it may have just solved the issue) ?
I never compile ToME, and didn't look at the code, so no idea how the mouse cursor is built.

**Comment by petevine** [comment]
On Tue, 01 Nov 2016 15:25:14 -0700
ptitSeb <notifications@github.com> wrote:

> did you retry with latest changes (with added Pixmap, PBuffer and multiple glX Context, it may have just solved the issue) ?

I was using the latest glshim master and it's still there. Any special options to try?

**Comment by ptitSeb** [comment]
Ah no. I need to look in the code to see how that cursor is built.

**Comment by petevine** [comment]
On Tue, 01 Nov 2016 15:55:25 -0700
ptitSeb <notifications@github.com> wrote:

> Ah no. I need to look in the code to see how that cursor is built.

Thanks!

**Comment by ptitSeb** [comment]
@petevine : it turned out it's not a glshim issue, but an SDL2 one. Check my github repo of SDL2, there is push about this: 604d108cf266f5e7fd1b1f3efd587e9f41004d23

**Comment by petevine** [comment]
Nice find! However, and I hope I'm not misremembering things, the white silhouette wasn't present on real hardware. Could the fix be incomplete?


![untitled](https://cloud.githubusercontent.com/assets/12054457/20025697/4682746e-a2f1-11e6-92ee-c2bf25016267.png)

**Comment by ptitSeb** [comment]
white silouette is there depending on the theme.

But if you want, you can change the `if(alpha==0)` by a `if(alpha<25)` to have something probably better (there are 2 way of putting cursor in X11 in SDL2, and the "legacy" way use something similar).

**Comment by petevine** [comment]
Yes, it's much better that way but it still looks artifactishly wide. The white background is not visible on x86/OpenGL 1.5, just a thin blue outline. I fired up my old Athlon box to take this picture :)

![untitled2](https://cloud.githubusercontent.com/assets/12054457/20033076/8eec57ae-a398-11e6-87dd-1631e12c8f53.jpg)

**Comment by ptitSeb** [comment]
Not much can be done here. It's X11 functions, and it seems they behave differently for machine to machine.
Play with the alpha stuff, put alpha<125 to remove moste of the semi-transparent stuff, or even up to <255 to just discard everything not solid color.

**Comment by ptitSeb** [comment]
For the record, here is the original PNG image.
![mouse](https://cloud.githubusercontent.com/assets/3250792/20033276/402a6a48-a39d-11e6-8100-80ea169cce81.png)

**Comment by ptitSeb** [comment]
And here the image for default theme.
![mouse](https://cloud.githubusercontent.com/assets/3250792/20033280/5b70defe-a39d-11e6-8973-983c7da8b146.png)
