### ISSUE TITLE
Gamma

### ISSUE THREAD

**Issue by CartridgeGen** [ptitSeb/glshim#3]
Re-Bonjour!

Je suis tres content d'utiliser le shim sur de nombreux applications. J'aimerais savoir si on pourrait faire fonctionner la ligne LIBGL_GAMMA sur ODROID. Je l'ai essayer avec mon program sans succes. Si je jouerai sur un monitor d'ordinateur, j'ai pas de probleme. Mais comme j'utilise mon ODROID sur une TV, le gamma est trop bas est je n'y voit rien. C'est pour cette raison je cite ceci ici et qu'il y a pas mieux moyen de te rejoindre. Merci beaucoup mon ami,

**Comment by ptitSeb** [comment]
Salut,

Oui, pour l'instant, le LIBGL_GAMMA est uniquement utilisable sur Pandora. Mais j'ai maintenant un ODROID-XU4 à la maison, je vais pouvoir regarder si je trouve une astuce pour gérer le gamma aussi... (sinon, je suis aussi sur le forum ODROID et sur le forum Pandora, toujours sous le pseudo de ptitSeb).

**Comment by CartridgeGen** [comment]
Merci mon ami! Je vais d'abord t'avertir de autres bugs s'il y a lieu dans le forum ODROID et garder les "Issues" nice&clean.
