### ISSUE TITLE
Managed to build glshim for android

### ISSUE THREAD

**Issue by tobimensch** [ptitSeb/glshim#4]
Then most of the undefined reference gl* errors went away when linking except for these:

error: undefined reference to 'glEnableVertexAttribArray'
 error: undefined reference to 'glVertexAttribPointer'
error: undefined reference to 'glDisableVertexAttribArray'

**Comment by ptitSeb** [comment]
You are trying to link something that need OpenGL 2.0 functions. glshim only support OpenGL up to 1.5 for now.

What are you trying to compile?

**Comment by tobimensch** [comment]
I looked it up and the functions seem to be part of glesv2.

I'm porting a small game to Android.

**Comment by ptitSeb** [comment]
Yes, there are part of GLESv2, but the glesv2 backend of glshim is not working. I plan to work on that, but much later. The GLESv2 part should not be activated.
The link error is during link of glshim or link of your game?

**Comment by tobimensch** [comment]
the link error is during link of the game!

**Comment by ptitSeb** [comment]
This game is probably not compatible with glshim for now, it need GL 2+ functions that are not available.

**Comment by tobimensch** [comment]
Isn't all the glshim needs to do to forward those calls to openglesv2?

**Comment by ptitSeb** [comment]
Yes and no.
If the game use a GLES2 compatible context, then yes (but in that case, you probably don't need glshim and can just link with libGLESv2.so).
GLSL langage between full GL and GLESv2 are different (not much, but still GLSL 1.0 from ES is a subsample of GL v1.20). Plus all fixed pipeline function should be emulated with GLES2 functions.
So, for most game, no, it's not that simple.

**Comment by tobimensch** [comment]
I can't just link with libGLESv2.so, because then I get many many more undefined references when linking.
Linking with with glshim eliminates almost all of these link errors except for these 3 functions above. I think the game is overwhelmingly opengl1.x and very little opengl2.0.

**Comment by tobimensch** [comment]
Here's a little information about those functions and what they are used for:

http://www.gamedev.net/topic/655785-is-glenablevertexattribarray-redundant/

Quote:
"Much of this is legacy from the old fixed pipeline (glEnable/DisableVertexAttribArray were modelled on glEnable/DisableClientState and first appeared in GL_ARB_vertex_program roundabout OpenGL 1.5: the older calls go back to 1.1) and dates to a time when you might be mixing vertex array drawing with immediate mode drawing.  So you'd use vertex arrays for your complex meshes and maybe glBegin/glEnd for your 2D GUI."

**Comment by ptitSeb** [comment]
If there is little to no GL 2.0, you can do the other way then.
Create some dimmys function yourself for those 3 function with;
```
void glEnableVertexAttribArray(GLuint index) { }
void glDisableVertexAttribArray(GLuint index); { }
void glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * pointer) { }
```

and it should link. Chance are it will not behave correctly if those functions are really used.

**Comment by tobimensch** [comment]
Unfortunately they are really used. :-(

**Comment by ptitSeb** [comment]
Is your game opensource (if yes, which one is it)? I can try to hack some kind of support for that, but I'm not sure I undestood how it really works / what is the expected behavour of thoses functions.

**Comment by ptitSeb** [comment]
It doesn't make much sense to have this function in fixed pipeline mode. I will probably close that ticket for now.
