### ISSUE TITLE
Remote

### ISSUE THREAD

**Issue by GFOXSH** [ptitSeb/glshim#6]
Can you add glshim remote? I'd like to test it in virtual machine.

**Comment by ptitSeb** [comment]
Not easily. I know it's in upstream, but both source code have derived heavily, making plugin some code from each other repo very difficult (i.e. you have to rewrite everything).

**Comment by GFOXSH** [comment]
Is it possible to compile a library of lunixbochs and run it on Android without X?

**Comment by ptitSeb** [comment]
You probably need to adapt a bit, not sure it has an Android.mk and the #ifdef to avoid X calls...

**Comment by GFOXSH** [comment]
Please give an example, what should I do?

**Comment by ptitSeb** [comment]
For the Android.mk, it's easy, you should take the version here https://github.com/ptitSeb/glshim/blob/master/Android.mk and adapt it (change the list of .c file basically).

For the #ifdef, it should be restricted to src/glx/*.c, look https://github.com/ptitSeb/glshim/blob/master/src/glx/glx.c#L518 for example.
Both glx.c files are still pretty similar, so copy/pasting should be doable without too much issues.

**Comment by GFOXSH** [comment]
Well, I've changed the file list in Android.mk.
So, I have to edit all the files in glx or simply replace glx.c?

**Comment by ptitSeb** [comment]
Copy will probably not work. You have to edit it.
You will have to edit lookup.c also. Basicaly, you just put #ifndef ANDROID ... #endif around function you don't want.

**Comment by GFOXSH** [comment]
Oh, tell me, please, do I correctly edit this?

GLXContext glXCreateContext(Display *dpy, XVisualInfo *vis, GLXContext shareList, Bool direct) {
    scan_env();
    FORWARD_IF_REMOTE(glXCreateContext);
    PROXY_GLES(glXCreateContext);
    LOAD_EGL(eglBindAPI);
    LOAD_EGL(eglChooseConfig);
    LOAD_EGL(eglCreateContext);
    LOAD_EGL(eglDestroyContext);
    LOAD_EGL(eglDestroySurface);
    LOAD_EGL(eglInitialize);
    LOAD_EGL(eglMakeCurrent);

    EGLint configAttribs[] = {
#ifndef ANDROID	
GLXContext glXCreateContext(Display *display,
                            XVisualInfo *visual,
                            GLXContext shareList,
                            Bool isDirect) {
//printf("glXCreateContext(%p, %p, %p, %i)\n", display, visual, shareList, isDirect);
EGLint configAttribs[] = {
#ifdef PANDORA
        EGL_RED_SIZE, 5,
        EGL_GREEN_SIZE, 6,
        EGL_BLUE_SIZE, 5,
#endif
        EGL_DEPTH_SIZE, 16,
#ifdef USE_ES2
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
#else
        EGL_BUFFER_SIZE, 16,
        EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES_BIT,
#endif
        EGL_NONE
    };

#ifdef USE_ES2
    EGLint attrib_list[] = {
        EGL_CONTEXT_CLIENT_VERSION, 2,
        EGL_NONE
    };
#else
    EGLint *attrib_list = NULL;
#endif

**Comment by ptitSeb** [comment]
Not really. If you look there: https://github.com/ptitSeb/glshim/blob/master/src/glx/glx.c#L518 you see that the whole function glXCreateContext is behind the `#ifndef ANDROID` ... `#endif`

**Comment by GFOXSH** [comment]
So, it's OK? I'm really bad in C...

GLXContext glXCreateContext(Display *dpy, XVisualInfo *vis, GLXContext shareList, Bool direct) {
    scan_env();
    FORWARD_IF_REMOTE(glXCreateContext);
    PROXY_GLES(glXCreateContext);
    LOAD_EGL(eglBindAPI);
    LOAD_EGL(eglChooseConfig);
    LOAD_EGL(eglCreateContext);
    LOAD_EGL(eglDestroyContext);
    LOAD_EGL(eglDestroySurface);
    LOAD_EGL(eglInitialize);
    LOAD_EGL(eglMakeCurrent);

    EGLint configAttribs[] = {
#ifndef ANDROID	
GLXContext glXCreateContext(Display *display,
                            XVisualInfo *visual,
                            GLXContext shareList,
                            Bool isDirect) {
//printf("glXCreateContext(%p, %p, %p, %i)\n", display, visual, shareList, isDirect);
    EGLint configAttribs[] = {
#ifdef PANDORA
        EGL_RED_SIZE, 5,
        EGL_GREEN_SIZE, 6,
        EGL_BLUE_SIZE, 5,
#endif
        EGL_DEPTH_SIZE, 16,
#ifdef USE_ES2
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
#else
        EGL_BUFFER_SIZE, 16,
        EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES_BIT,
#endif
        EGL_NONE
    };

#ifdef USE_ES2
    EGLint attrib_list[] = {
        EGL_CONTEXT_CLIENT_VERSION, 2,
        EGL_NONE
    };
#else
    EGLint *attrib_list = NULL;
#endif


    if (g_bcmhost && !g_bcm_active) {
        g_bcm_active = true;
        bcm_host_init();
    }

**Comment by ptitSeb** [comment]
looks ok, but there are other function that should have the same treatment. Find all ANDROID occurrence to know wich function should be ifdefed.

**Comment by GFOXSH** [comment]
Thank you! I try to do it.

**Comment by GFOXSH** [comment]
I do not know how to insert some ifndef ... You could not make these files?

**Comment by ptitSeb** [comment]
I'll see what I can do later.

**Comment by GFOXSH** [comment]
Good morning! I try again. It's OK?
[glx.txt](https://github.com/ptitSeb/glshim/files/375080/glx.txt)

**Comment by ptitSeb** [comment]
I'll check in a few hours.

**Comment by GFOXSH** [comment]
Thank you in advance!

**Comment by GFOXSH** [comment]
And, please, check lookup.c:
[lookup.txt](https://github.com/ptitSeb/glshim/files/375495/lookup.txt)

**Comment by ptitSeb** [comment]
I don't understand, the glx.txt file, it's mine?

(you will also need to change glx.h).

**Comment by GFOXSH** [comment]
No, it glx.c with some changes made in comparison to your files.

**Comment by GFOXSH** [comment]
It is glx.h:
[glx.txt](https://github.com/ptitSeb/glshim/files/375782/glx.txt)

**Comment by ptitSeb** [comment]
The glx.c looks ok, but there are many things that should not be there
(like all the pandora_gamma stuff). Not sure it will link properly.

2016-07-21 13:15 GMT+02:00 GFOXSH <notifications@github.com>:

**Comment by GFOXSH** [comment]
I removed the part of the code relating to Pandrora. That's better?
[Uploading glx.txt…]()

**Comment by GFOXSH** [comment]
@ptitSeb can I use proxy from your glshim library? As far as I understand, it client-server system is implemented?

**Comment by ptitSeb** [comment]
Nope, no client-server stuff at all on my version.

**Comment by GFOXSH** [comment]
Oh, sorry, host and client: https://github.com/ptitSeb/glshim/tree/master/src/proxy

**Comment by ptitSeb** [comment]
That part wont help you.

**Comment by GFOXSH** [comment]
Hrmm... How it works?

**Comment by GFOXSH** [comment]
Is it possible to run in a virtual machine host, that he acted as a driver, and the client requests received and wrap OpenGL? My friend did it on Debian via lunixbochs glshim...

**Comment by ptitSeb** [comment]
Yes, I know the mecanics, but only lunixbochs version can do that.

**Comment by GFOXSH** [comment]
OK, OK... So, what about https://github.com/ptitSeb/glshim/issues/6#issuecomment-234241570 ?

**Comment by GFOXSH** [comment]
Please, check all files for error and tell me about problems. Thank you very much in advance!

**Comment by GFOXSH** [comment]
Or, can you add this https://github.com/mittorn/glshim feature to your glshim?

**Comment by ptitSeb** [comment]
what feature? It's a fork, but I see nothing changed compared to original version.

**Comment by GFOXSH** [comment]
Look-like I see ExaGear proxy feature on this commit: https://github.com/mittorn/glshim/commit/476e1b6c277d435c18feaf5f05839fe847655925

**Comment by ptitSeb** [comment]
Probably, but I don't support ExaGear, and I have no intention to add support for it. 
I don't own it and will not buy it.

**Comment by ptitSeb** [comment]
RemoteGL is not a planed feature. Closing this ticket.
