### ISSUE TITLE
Spinning selector garbled in FO

### ISSUE THREAD

**Issue by petevine** [ptitSeb/glshim#8]
I remember pointing out in a comment under one of the commits, the in-game system selector was not being animated in FreeOrion.

However, a year later and after compiling FO 0.4.6 + latest glshim, it seems it became animated
and looks like a garbled square. I'll try finding the comment that IIRC, linked to some C++ code.

![fo](https://cloud.githubusercontent.com/assets/12054457/19419088/6b60b546-93d0-11e6-82a6-3b341cd2f83a.jpg)

**edit:**
Here it is: https://github.com/ptitSeb/glshim/commit/9d4dbc6b663a50df721031e8997333602d45d27e#commitcomment-14491488

In stop-motion, in would probably look exactly like on the right.

**Comment by ptitSeb** [comment]
Ok, I reproduce the issue on side. I'll try to fix that.

**Comment by ptitSeb** [comment]
@petevine has a temporary workaround, you can use `LIBGL_NOLUMALPHA=1`
![freeorion01](https://cloud.githubusercontent.com/assets/3250792/19420235/7270a4ba-93e7-11e6-946d-1048beff6296.png)

**Comment by petevine** [comment]
Cool, nice to see the little detail's working too!

**Comment by ptitSeb** [comment]
Ok, fixed with https://github.com/ptitSeb/glshim/commit/f6ad89c28730c6ed826689c42c84409ad77901ae

**Comment by petevine** [comment]
Thanks! BTW, it seems LIBGL_BATCH produces a white square instead of a garbled one :)

**Comment by ptitSeb** [comment]
I haven't tried LIBGL_BATCH with this one yet, but I will.
