### ISSUE TITLE
Problems while compiling for Android

### ISSUE THREAD

**Issue by raduprv** [ptitSeb/glshim#9]
Hi

I am having some trouble compiling it on Android.
I am getting a few warnings, such as:
In file included from jni/glshim/src/gl/wrap/../gl.h:358:
jni/glshim/src/gl/stack.h:140:3: warning: redefinition of typedef 'glstack_t' is

```
  a C11 feature [-Wtypedef-redefinition]
```

} glstack_t;
  ^
jni/glshim/src/gl/state.h:11:27: note: previous definition is here
typedef struct _glstack_t glstack_t;
                          ^
In file included from jni/glshim/src/gl/array.c:1:
In file included from jni/glshim/src/gl/array.h:1:
In file included from jni/glshim/src/gl/wrap/../gl.h:358:
jni/glshim/src/gl/stack.h:165:3: warning: redefinition of typedef
      'glclientstack_t' is a C11 feature [-Wtypedef-redefinition]
} glclientstack_t;
  ^
jni/glshim/src/gl/state.h:12:33: note: previous definition is here
typedef struct _glclientstack_t glclientstack_t;

I am also getting an error:
                                ^
jni/glshim/src/gl/array.c:211:9: error: invalid suffix 'd' on floating constant
        GL_TYPE_SWITCH_MAX(out, dst, to,
        ^
jni/glshim/src/gl/wrap/../gl.h:180:64: note: expanded from macro
      'GL_TYPE_SWITCH_MAX'
  ...GL_TYPE_CASE_MAX(name, var, GL_DOUBLE, GLdouble, code, 1.0d)         \
                                                               ^
2 warnings and 1 error generated.
make: **\* [obj/local/armeabi/objs/glshim/src/gl/array.o] Error 1

Any ideas?

**Comment by ptitSeb** [comment]
I guess you are using CLang has a tool chain. It seems more picky than gcc about the typedef. Thoses warning should be harmless.
That error is strange, but I can fix it.

**Comment by ptitSeb** [comment]
@raduprv : should be fixed with 94ac4c6440e98a176079b5aab9418a340ad20faf

**Comment by raduprv** [comment]
Thanks, that fixed the problem, but now I have a different, unrelated error (and some new warnings). And yes, I am using CLANG, the latest versions of the NDK use CLANG now.

jni/glshim/src/glx/glx.c:119:31: error: unknown type name 'Display'
static int get_config_default(Display *display, int attribute, int *value) {
                              ^
jni/glshim/src/glx/glx.c:162:22: warning: implicit declaration of function
      'glXChooseVisual' is invalid in C99 [-Wimplicit-function-declaration]
            *value = glXChooseVisual(display, 0, NULL)->visualid;
                     ^
jni/glshim/src/glx/glx.c:308:31: warning: implicit declaration of function
      'backtrace' is invalid in C99 [-Wimplicit-function-declaration]
                size_t size = backtrace(array, 10);
                              ^
jni/glshim/src/glx/glx.c:313:21: warning: implicit declaration of function
      'backtrace_symbols_fd' is invalid in C99 [-Wimplicit-function-declaration]

**Comment by ptitSeb** [comment]
That one will probably take more time

**Comment by raduprv** [comment]
Is this also a Clang specific problem?
If so, I think I will have a lot of fun porting my program to Android. I am just building the libs right now.

**Comment by ptitSeb** [comment]
No, it's not CLang, it's my latest commit about PBuffer and the fact that everything X11 related is not available in Android.

**Comment by raduprv** [comment]
Is that really needed? I mean, if not, you can maybe #ifdef it out for ANDROID until you can find some elegant fix :)

**Comment by ptitSeb** [comment]
Yeah I know, but in fact, that was supposed to be done already! Obviously, I have missed a few things...

**Comment by ptitSeb** [comment]
Maybe it's fixed with 82b7884affc0ed85765810b7da629a4fc2187772 @raduprv , you can try.

**Comment by raduprv** [comment]
It compiled and linked, thanks!
Didn't get to try it yet though, because I still have quite a bit of work until I get the project ported. Right now I am stuck at cal3d :/

Anyway, thanks for your time and prompt fix! I will let you know if/how it works when I manage to get my game working :)

**Comment by ptitSeb** [comment]
Ok.

Good luck with your project!

**Comment by raduprv** [comment]
Thanks!
On a side note, would you be interested to help us porting it? (for money, of course).

**Comment by raduprv** [comment]
Ok, now I am having other problems.
After my code finally compiled, I am getting a lot of undefined references:
Any ideas? Am I doing something wrong?

jni/glshim/src/gl/gl.c:308: error: undefined reference to 'load_libs'
jni/glshim/src/gl/gl.c:427: error: undefined reference to 'gles'
jni/glshim/src/gl/gl.c:427: error: undefined reference to 'gles'
jni/glshim/src/gl/gl.c:431: error: undefined reference to 'load_libs'
jni/glshim/src/gl/gl.c:510: error: undefined reference to 'gles'
jni/glshim/src/gl/gl.c:510: error: undefined reference to 'gles'
jni/glshim/src/gl/gl.c:654: error: undefined reference to 'load_libs'
jni/glshim/src/gl/gl.c:680: error: undefined reference to 'load_libs'
jni/glshim/src/gl/gl.c:1828: error: undefined reference to 'egl'
jni/glshim/src/gl/gl.c:1828: error: undefined reference to 'egl'
jni/glshim/src/gl/gl.c:1846: error: undefined reference to 'egl'
jni/glshim/src/gl/gl.c:1846: error: undefined reference to 'egl'

**Comment by raduprv** [comment]
Ok, I think I found the problem...
The android make file lacks 	src/gl/loader.c \
Also, any reason why there is -DBCMHOST in the android make file?

**Comment by ptitSeb** [comment]
Ah yes, the Android.mk! It's fixed with 1236d679bf0d8d0cbf1437f085dd1ac289994201

For BCMHOST, no particular reason, but anyway, the BroadCom specifics feature are dynamicaly loaded, and called only if broadcom libs are present, so it's safe to keep it.

**Comment by raduprv** [comment]
Thanks!

One more thing. I am trying to build it as a shared lib, with BUILD_SHARED_LIBRARY, and I am getting some errors. It works fine as a static lib though.

jni/glshim/src/gl/array.c:41: error: undefined reference to '__android_log_print
'
jni/glshim/src/gl/wrap/../gl.h:241: error: undefined reference to '__android_log
_print'
jni/glshim/src/gl/wrap/../gl.h:241: error: undefined reference to '__android_log
_print'
jni/glshim/src/gl/array.c:41: error: undefined reference to '__android_log_print
'
jni/glshim\include/android_debug.h:60: error: undefined reference to '__android_
log_vprint'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invoca
tion)
make: *** [obj/local/armeabi/libglshim.so] Error 1

**Comment by ptitSeb** [comment]
Probably missing "-llog" in the Android.mk

**Comment by raduprv** [comment]
Nope, wasn't missing it. Same without -lEGL

Here is my complete make file:

LOCAL_PATH := $(call my-dir)

###########################
#
# GL static library
#
###########################

include $(CLEAR_VARS)

LOCAL_MODULE := glshim

LOCAL_C_INCLUDES := $(LOCAL_PATH)/include \
	$(LOCAL_PATH)/src/util \
	$(LOCAL_PATH)/src/util/vectorial

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES) -DBCMHOST

LOCAL_SRC_FILES := \
	src/gl/array.c \
	src/gl/buffers.c \
	src/gl/debug.c \
	src/gl/decompress.c \
	src/gl/directstate.c \
	src/gl/eval.c \
	src/gl/framebuffers.c \
	src/gl/gl.c \
	src/gl/light.c \
	src/gl/loader.c \
	src/gl/line.c \
	src/gl/list.c \
	src/gl/pixel.c \
	src/gl/raster.c \
	src/gl/queries.c \
	src/gl/render.c \
	src/gl/stack.c \
	src/gl/texgen.c \
	src/gl/texture.c \
	src/gl/wrap/gl.c \
	src/gl/wrap/gles.c \
	src/gl/wrap/gles2.c \
	src/gl/wrap/glesext.c \
	src/gl/wrap/glstub.c \
	src/gl/math/eval.c \
	src/glx/glx.c \
	src/glx/lookup.c \
	src/glx/streaming.c \

LOCAL_CFLAGS += -g -std=c99 -funwind-tables -O3 -DBCMHOST -include include/android_debug.h

#LOCAL_LDLIBS := -ldl -llog

include $(BUILD_SHARED_LIBRARY)

**Comment by ptitSeb** [comment]
remove the "#" before LOCAL_LDLIBS ;)

**Comment by raduprv** [comment]
Lol, that was stupid! Thanks, no idea how I missed it :)
It now builds OK!

**Comment by lubomyr** [comment]
after latest changes Android.mk file requires adding one new line
    src/gl/queries.c \

2016-10-21 22:56 GMT+03:00 raduprv <notifications@github.com>:

**Comment by raduprv** [comment]
It was there already :)

**Comment by raduprv** [comment]
Well, how can I contact you directly? E-mail, skype, etc?
I got my source to compile and run, but I am getting some Gl related errors that I am trying to track down. Is there a way to make glshim give more verbose output?

**Comment by raduprv** [comment]
I am having a problem with glEnable(GL_TEXTURE_2D);
It gives me: W/Adreno-ES20(11245): <process_gl_state_enables:519>: GL_INVALID_ENUM

Any ideas? :/

**Comment by ptitSeb** [comment]
You are using GLES2, wich is not supported for now. Only GLES 1.1 is. Strange that it load this lib. Did you compile with ES2 define? I will remove this define a some point in the future anyway, GLES2 will be done differently.

**Comment by raduprv** [comment]
I removed the GLES2 from the linking libs, and my application is SDL2/OpenGL. No ES2 or GLES define in my code (that I know of).

**Comment by raduprv** [comment]
Also:
I/glshim  (12258): libGL:loaded: libGLESv1_CM.so
I/glshim  (12258): libGL:loaded: libEGL.so
No other libs are loaded (by glshim at least).

**Comment by ptitSeb** [comment]
Also, if the game you are trying to port is Eternal Lands, you will have issue, probably, with the current method used to get "object under the mouse". It use many ReadPixels that just kill the performances of some GLES Hardware (PVR for example) and also make a readpixel on the DEpth which is not supported in GLES Hardware.
I have a planed workaround for that, but I haven't finished implementing it, I just barelly started it some time ago.

(you can contact me by mail, on my gmail adress).

**Comment by ptitSeb** [comment]
If you are using SDL2/OpenGL, you have to make  sure SDL2 is built for desktop OpenGL and not GLES only.

**Comment by ptitSeb** [comment]
So EGL & GLESv1_CM are loaded, good. the glEnable(GL_TEXTURE2D) should not gives an error (unless the error comes from previous call maybe)?

**Comment by raduprv** [comment]
Great, can you give me your mail address? I can't find it anywhere :/
And we have a new way of reading the object under the mouse :) Besides, on android that would be a problem anyway, as you can only read it during a tap.

**Comment by raduprv** [comment]
No, the error comes from there, I check after every call:

	glEnable(GL_DEPTH_TEST);
	SDL_Log("Done depth");
	glDepthFunc(GL_LESS);
	SDL_Log("Done depth less");
	//glDepthFunc(GL_LEQUAL);
	glEnable(GL_TEXTURE_2D);
	SDL_Log("Done texture");
	glShadeModel(GL_SMOOTH);
	SDL_Log("Done smooth");
	glFrontFace(GL_CCW);
	SDL_Log("Done CCW");
	glCullFace(GL_BACK);
	SDL_Log("Done BACK");
	glEnable(GL_NORMALIZE);
	SDL_Log("Done Normalize");
	glClearStencil(0);

I/SDL/APP (12258): Done depth
I/SDL/APP (12258): Done depth less
W/Adreno-ES20(12258): <process_gl_state_enables:519>: GL_INVALID_ENUM
I/SDL/APP (12258): Done texture
E/libEGL  (12258): called unimplemented OpenGL ES API
I/SDL/APP (12258): Done smooth
I/SDL/APP (12258): Done CCW
I/SDL/APP (12258): Done BACK
I/SDL/APP (12258): Done Normalize
I/SDL/APP (12258): Done with first block

If those two libs are loaded, is there any need to compile SDL2 with desktop opengl?

**Comment by ptitSeb** [comment]
Still seems that SDL2 is staticaly linked with GLES2? Can you check that?

**Comment by lubomyr** [comment]
As i remember official SDL2 for android in Android.mk uses GLESv2
I ported a lot app with glshim, but i used pelya's libSDL (not official)

**Comment by ptitSeb** [comment]
Good to know there is a new method, as the old one prevented me to port it on the Pandora before.

For my mail, look here: https://www.youtube.com/watch?v=R6j9a1RShuI you should find it :)

**Comment by raduprv** [comment]
Yes, SDL2 was linked with GLES2 as well. I changed that, compiling now.

**Comment by raduprv** [comment]
Nope, still the same error :/
In my logs, it says:
I/OpenGLRenderer(13385): Initialized EGL, version 1.4
D/OpenGLRenderer(13385): Enabling debug mode 0

So I guess there is no GLES2 anywhere...
Either way, I couldn't find the e-mail from that video or from the youtube page (unless if I am missing something)

**Comment by ptitSeb** [comment]
here: sebastien.chev@gmail.com

**Comment by ptitSeb** [comment]
Android build is working now. I close this ticket.
